"""add_medications_table

Revision ID: 65034392a274
Revises: e7d80afcd1d0
Create Date: 2025-11-06 21:47:30.974144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65034392a274'
down_revision = 'e7d80afcd1d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anvisa_registry', sa.String(length=50), nullable=True),
    sa.Column('commercial_name', sa.String(length=500), nullable=False),
    sa.Column('active_ingredient', sa.String(length=500), nullable=False),
    sa.Column('presentation', sa.String(length=500), nullable=True),
    sa.Column('concentration', sa.String(length=100), nullable=True),
    sa.Column('pharmaceutical_form', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=300), nullable=True),
    sa.Column('therapeutic_class', sa.String(length=200), nullable=True),
    sa.Column('requires_prescription', sa.Integer(), nullable=True),
    sa.Column('ean_code', sa.String(length=20), nullable=True),
    sa.Column('pmc', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anvisa_registry')
    )
    op.create_index(op.f('ix_medications_active_ingredient'), 'medications', ['active_ingredient'], unique=False)
    op.create_index(op.f('ix_medications_commercial_name'), 'medications', ['commercial_name'], unique=False)
    op.create_index(op.f('ix_medications_manufacturer'), 'medications', ['manufacturer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medications_manufacturer'), table_name='medications')
    op.drop_index(op.f('ix_medications_commercial_name'), table_name='medications')
    op.drop_index(op.f('ix_medications_active_ingredient'), table_name='medications')
    op.drop_table('medications')
    # ### end Alembic commands ###
