"""add_signatures_table

Revision ID: d656e7e8d0ea
Revises: 97cb65df65f6
Create Date: 2025-11-08 02:22:30.491751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd656e7e8d0ea'
down_revision = '97cb65df65f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'google_calendar_event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('google_calendar_event_id', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
