"""add_organizations_table_and_update_users

Revision ID: e7d80afcd1d0
Revises: 601bcdb3a6ff
Create Date: 2025-11-06 16:00:34.180004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7d80afcd1d0'
down_revision = '601bcdb3a6ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('state_registration', sa.String(length=50), nullable=True),
    sa.Column('municipal_registration', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_number', sa.String(length=20), nullable=True),
    sa.Column('address_complement', sa.String(length=100), nullable=True),
    sa.Column('address_neighborhood', sa.String(length=100), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zipcode', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('logo_small_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('header_text', sa.Text(), nullable=True),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('allow_multiple_users', sa.Boolean(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.alter_column('appointments', 'healthcare_professional_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('appointments', 'scheduled_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('appointments', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index('ix_appointments_appointment_date', table_name='appointments')
    op.drop_index('ix_appointments_tenant_id', table_name='appointments')
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.drop_column('appointments', 'tenant_id')
    op.drop_column('appointments', 'professional_id')
    op.drop_column('appointments', 'appointment_date')
    op.add_column('prescription_templates', sa.Column('is_sent', sa.Boolean(), nullable=True))
    op.add_column('prescription_templates', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_column('prescription_templates', 'sent_at')
    op.drop_column('prescription_templates', 'is_sent')
    op.add_column('appointments', sa.Column('appointment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('professional_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.create_index('ix_appointments_tenant_id', 'appointments', ['tenant_id'], unique=False)
    op.create_index('ix_appointments_appointment_date', 'appointments', ['appointment_date'], unique=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('appointments', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'scheduled_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('appointments', 'healthcare_professional_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_table('organizations')
    # ### end Alembic commands ###
